# https://taskfile.dev

version: '3'

tasks:
  default:
    deps:
      - task: fmt
      - task: lint
      - task: test
  check:
    deps:
      - task: test
      - task: lint
  test:
    cmds:
      - echo 'Update here'
  fmt:
    cmds:
      - dprint fmt
      - git ls-files '*.nix' | xargs nix fmt
      - yamlfmt .
      - shfmt --write ./images/*/*.bash
  lint:
    cmds:
      - dprint check
      - yamlfmt -lint .
      - typos . .github .vscode
      - git ls-files '*.nix' | xargs nixfmt --check
      - trivy config --exit-code 1 .
      - shellcheck ./images/*/*.bash
  'try:systemd':
    cmds:
      - ./images/ubuntu-nix-systemd/try.bash '{{.USER}}'
  'try:sudoer':
    cmds:
      - ./images/ubuntu-nix-sudoer/try.bash '{{.USER}}'
  deps:
    cmds:
      - nix --version
      - nil --version
      - task --version
      - dprint --version
      - yamlfmt -version
      - typos --version
      - trivy --version
